---
- hosts: webservers
  become: true
  tasks:
    - name: Install Apache2 on Ubuntu
      apt:
        name: apache2
        state: present

    - name: Start Apache2 on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Add firewall rule for HTTP on Ubuntu
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Copy index.html to Apache document root on Ubuntu
      copy:
        src: "/var/lib/jenkins/workspace/ansible/index.html"
        dest: "/var/www/html/index.html"
        remote_src: yes


